--- 
kategorienText: "Kategorien: "
tagsText: " / Schlagworte: "
creativecommonsText: "Dieses Werk ist lizenziert unter <a rel='license' href='https://creativecommons.org/licenses/by-sa/4.0/'>Creative Commons Namensnennung-Weitergabe unter gleichen Bedingungen 4.0 international</a>."
